configName: sam_e54_xpro_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: aws_cloud;bootloader;bsp;core;crypto;cryptoauthlib;csp;expresslogic_threadx;gfx;gfx_apps;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.2.60\atdf\ATSAME54P20A.atdf
