format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_spi}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_SPI_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_spi, value: Synchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_spi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SPI_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: Synchronous}
      - type: String
        attributes: {id: DRV_SPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: SERCOM4}
      - type: Integer
        attributes: {id: DRV_SPI_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '1'}
      - type: Integer
        attributes: {id: DRV_SPI_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_0, value: '0'}
      - type: Boolean
        attributes: {id: DRV_SPI_TX_RX_DMA}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_spi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sercom4}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SERCOM4_SPI}
  - type: InstanceComponent
    attributes: {instance: '1', id: drv_spi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SPI_MODE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_1, value: Synchronous}
      - type: String
        attributes: {id: DRV_SPI_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_1, value: SERCOM6}
      - type: Integer
        attributes: {id: DRV_SPI_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_1, value: '3'}
      - type: Integer
        attributes: {id: DRV_SPI_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_spi_1, value: '2'}
      - type: Boolean
        attributes: {id: DRV_SPI_TX_RX_DMA}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: 'true'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_spi_SPI_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sercom6}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SERCOM6_SPI}
- type: ElementPosition
  attributes: {x: '344', y: '104', id: drv_spi}
