configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: aerospace;aws_cloud;bootloader;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;motor_control;net;touch;usb;wireless;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.2.53\atdf\ATSAME54P20A.atdf
